# execute_process( COMMAND git describe --abbrev=7 --dirty --always --all --long
# OUTPUT_VARIABLE CURRENT_GIT_DESCRIBE OUTPUT_STRIP_TRAILING_WHITESPACE)

set(DEPLOYED_MAJOR 1)
set(DEPLOYED_MINOR 22)

message(STATUS "CURRENT DEPLOY VERSION: ${DEPLOYED_MAJOR}.${DEPLOYED_MINOR}")
configure_file(${VERSION_TEMPLATE_FILE} ${VERSION_SOURCE_FILE} @ONLY)
